### ISSUE TITLE
Bug in manual installation steps

### ISSUE THREAD

**Issue by lingfors** [kumardeepakr3/PINTOS-Ubuntu#1]
In the description for manual installation steps, in step 11:

"export PATH=$/home/.../pintos/src/utils:$PATH"

is incorrect. It should be:

"export PATH=/home/.../pintos/src/utils:$PATH"

(Notice the missing "$" sign between "... PATH=" and "/home..:".)

**Comment by kumardeepakr3** [comment]
Thanks @lingfors . Will fix this.

**Comment by kumardeepakr3** [comment]
Done.
