### ISSUE TITLE
Error after autoinstallation

### ISSUE THREAD

**Issue by 0xJchen** [kumardeepakr3/PINTOS-Ubuntu#2]
Environment: ubuntu18.04
After the autoinstallation, I type 
`pintos -h` to test, and it prompt:
`Unrecognized character \x16; marked by <-- HERE after   if ($<-- HERE near column 7 at /root/proj/PINTOS-Ubuntu/pintos/src/utils/pintos line 911.`
And I found line 911 is like this:
` if ($^V ge 5.8.0) {`
What should I do next?

**Comment by kumardeepakr3** [comment]
Hey @PeppaCat , please use the source code from here: https://github.com/WyldeCat/pintos-anon
The one that I have is old and worked for Ubuntu 16.04.

**Comment by kumardeepakr3** [comment]
You can watch this video for installation on Ubuntu 18.04.
https://www.youtube.com/watch?v=CI5FHJhXv38&ab_channel=Nh%E1%BA%ADtL%C3%AADuy

**Comment by 0xJchen** [comment]
Hi, thank you for replying! I followed that manually again and still met the same problem:
`Unrecognized character \x16; marked by <-- HERE after   if ($<-- HERE near column 7 at /root/pintos/src/utils/pintos line 911.` on Ubuntu 18.04.
Could you please give me some suggestions on it?

**Comment by 0xJchen** [comment]
> Hi, thank you for replying! I followed that manually again and still met the same problem:
> `Unrecognized character \x16; marked by <-- HERE after if ($<-- HERE near column 7 at /root/pintos/src/utils/pintos line 911.` on Ubuntu 18.04.
> Could you please give me some suggestions on it?

Hi, for others who are suffering from this problem, the solution is not to use the pintos version in this repo, instead, please use the new official  version. The developer has fixed this bug. More information can be find here:
https://stackoverflow.com/questions/45656966/how-to-resolve-pintos-unrecognized-character-x16

**Comment by kumardeepakr3** [comment]
> Hey @PeppaCat , please use the source code from here: https://github.com/WyldeCat/pintos-anon
> The one that I have is old and worked for Ubuntu 16.04.

As mentioned above - The code given in the above github repo has the fix suggested in the github repo. I don't know why you should be getting the error again.
